version: '3.8'

services:
  # Реляционная БД
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db0

  # Time Series DB
  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=myorg
      - DOCKER_INFLUXDB_INIT_BUCKET=mybucket
    volumes:
      - influxdb_data:/var/lib/influxdb2

  # Векторная БД
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - ALLOW_RESET=TRUE
    volumes:
      - chromadb_data:/chroma/chroma
    ports:
      - "8000:8000"

  # Графовая БД
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      NEO4J_AUTH: neo4j/password123

  # Колоночная БД
  clickhouse:
    image: clickhouse/clickhouse-server:23.8
    ports:
      - "8123:8123"  # HTTP
      - "9000:9000"  # Native
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  # In-Memory БД
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # Геопространственная БД
  tile38:
    image: tile38/tile38:latest
    ports:
      - "9851:9851"

volumes:
  postgres_data:
  influxdb_data:
  minio_data:
  clickhouse_data:
  chromadb_data:
  mongodb_data: